[supervisord]
nodaemon=true
logfile=/var/log/supervisor/supervisord.log
pidfile=/var/run/supervisord.pid
childlogdir=/var/log/supervisor

[program:rasa-server]
command=rasa run --enable-api --cors "*" --port 5005 --model models/modelo_uft.tar.gz --endpoints endpoints.yml
directory=/app
autostart=true
autorestart=true
stderr_logfile=/var/log/supervisor/rasa-server.err.log
stdout_logfile=/var/log/supervisor/rasa-server.out.log
environment=PYTHONPATH="/app",RASA_LOG_LEVEL="INFO"

[program:rasa-actions]
command=rasa run actions --actions actions --port 5055
directory=/app
autostart=true
autorestart=true
startsecs=15
stderr_logfile=/var/log/supervisor/rasa-actions.err.log
stdout_logfile=/var/log/supervisor/rasa-actions.out.log
environment=PYTHONPATH="/app",RASA_LOG_LEVEL="INFO"